workspace = { members = ["fs-scout-macros"] }
[package]
name = "fs-scout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs-scout-macros = { path = "fs-scout-macros" }
